[steps]

[steps.analyze_metadata]
prompt = """
Проанализируйте диалог и выведите:

1. Тему встречи (1 предложение)
2. Участников в формате:

SPEAKER_XX (Имя, если упомянуто)
- Роль: <должность/функция>

Пример:
Интеграция SAP ERP с новой CRM-системой

SPEAKER_00 (Дима)
- Роль: Эксперт по SAP

SPEAKER_01 (Михаил)
- Роль: Project Manager
"""
temperature = 0.0

[steps.analyze_speakers]
prompt = """
Я предоставил JSON-файл с распознанным диалогом деловой встречи.
Диалог содержит поля "speaker" (с условными идентификаторами как SPEAKER_01) и "message" с текстом реплики.

Пожалуйста:

1. Проанализируйте весь диалог и определите:
   - Сколько уникальных спикеров участвовало (по идентификаторам SPEAKER_XX)
   - Их предполагаемые имена, если они упоминаются в тексте диалога
   - Их вероятные роли, основываясь на:
     а) Как к ним обращаются
     б) О чем они говорят
     в) Какие решения принимают
     г) Какие задачи назначают

2. Для каждого спикера укажите:
   - Условный ID (SPEAKER_XX)
   - Предполагаемое имя (если найдено в диалоге)
   - Вероятную роль
   - 2-3 ключевые фразы из диалога, подтверждающие роль

3. Примерный процент участия в беседе:
   - XX %

4. Уровень уверенности в определении:
   - Высокий (явно указано в диалоге)
   - Средний (есть косвенные признаки)
   - Низкий (предположение по контексту)   

Если есть неопределенность в идентификации участников или их ролей, пожалуйста, отметьте это явно.
"""
temperature = 0.0

[steps.analyze_recognition_errors]
prompt = """
Я предоставил JSON-файл с распознанным диалогом технической встречи.
В тексте могут быть ошибки автоматического распознавания, особенно в:
- Технических терминах
- Аббревиатурах
- Названиях технологий, продуктов, команд
- Профессиональном жаргоне

Пожалуйста, проанализируйте текст и найдите потенциальные ошибки распознавания, используя следующие критерии:

1. Слова и фразы, которые:
   - Не имеют смысла в контексте обсуждения
   - Похожи по звучанию на технические термины
   - Выглядят как искаженные аббревиатуры
   - Нарушают техническую терминологию

2. Для каждой найденной потенциальной ошибки укажите:
   - Исходный текст: как записано в распознавании
   - Предполагаемый правильный вариант
   - Контекст: часть предложения для подтверждения
   - Уверенность в коррекции: высокая/средняя/низкая

Представьте результат в виде таблицы:
| Исходный текст | Правильный вариант | Контекст | Уверенность |
|----------------|-------------------|-----------|-------------|

Если для одного исходного текста возможно несколько вариантов коррекции, укажите их в порядке убывания вероятности.

Ответом должна быть только таблица. Без дополнительных пояснений.
"""
temperature = 0.0

[steps.generate_summary]
prompt = """
Я предоставил распечатку деловой встречи, полученную через автоматическое распознавание речи.
В тексте могут быть ошибки распознавания, особенно в профессиональных терминах и аббревиатурах.

<<TOPIC_AND_ROLES>>

Известные ошибки распознавания:
<<RECOGNITION_ERRORS>>

Пожалуйста, проанализируйте текст встречи и предоставьте резюме в следующем формате:

1. Основные обсуждаемые темы (3-5 ключевых тем)
2. По каждой теме:
   - Краткое описание обсуждения
   - Принятые решения
   - Назначенные ответственные (если указаны)
   - Сроки (если обозначены)
3. Список согласованных следующих действий:
   - Что нужно сделать
   - Кто ответственный
   - К какому сроку
4. Открытые вопросы, требующие дополнительного обсуждения

При составлении резюме:
- Использовать правильные технические термины согласно таблице ошибок распознавания
- Идентифицировать и указывать конкретные системы и платформы
- Четко разделять основное решение и альтернативные варианты
- Сохранять деловой, но не формальный стиль изложения
- Включать @mentions участников, если они упоминаются в контексте задач
- Избегать излишней структурированности и формальности в тексте

Ответ сформулируй с использованием разметки MD
"""
# prompt = """
# Я предоставил распечатку деловой встречи, полученную через автоматическое распознавание речи.
# В тексте могут быть ошибки распознавания, особенно в профессиональных терминах и аббревиатурах.

# <<TOPIC_AND_ROLES>>

# Известные ошибки распознавания:
# <<RECOGNITION_ERRORS>>

# Пожалуйста, проанализируйте текст встречи и предоставьте резюме в следующем формате:

# **Обсудили:**
# - Основные темы обсуждения в виде маркированного списка
# - Фокус на ключевых технических деталях и упомянутых системах
# - Включать только существенные моменты дискуссии, избегая излишней детализации
# - При необходимости группировать связанные темы

# **Решили:**
# - Конкретные принятые решения
# - Назначенные задачи с указанием ответственных через @username
# - Основной путь решения
# - Альтернативные варианты решения с указанием их приоритетности

# При составлении резюме:
# - Использовать правильные технические термины согласно таблице ошибок распознавания
# - Идентифицировать и указывать конкретные системы и платформы
# - Четко разделять основное решение и альтернативные варианты
# - Сохранять деловой, но не формальный стиль изложения
# - Включать @mentions участников, если они упоминаются в контексте задач
# - Избегать излишней структурированности и формальности в тексте

# Ответ сформулируй с использованием разметки MD
# """
temperature = 0.0


[steps.refine_summary]
prompt = """
Ранее предоставлена распечатка деловой встречи.

Тема и участники:
<<TOPIC_AND_ROLES>>

Известные ошибки распознавания:
<<RECOGNITION_ERRORS>>

Предыдущее саммари встречи:
<<PREV_RESUME>>

---
Создайте новое саммари примерно той же длины (±5 слов), которое:
- Сохранит всю существенную информацию из предыдущего саммари
- Добавит 2-3 новых важных элемента из исходного текста (технические детали, решения, задачи, @mentions)
- Улучшит четкость формулировок
- Исправит технические термины согласно справочнику

Формат ответа (в формате MD):
<NewElements>
- [список добавленных элементов по сравнению с предыдущим саммари]
</NewElements>

# Саммари
[текст саммари]
"""
temperature = 0.0
